PhotoGallery/Controllers/AddPhotoController.cs
using PhotoGallery.Models;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhotoGallery.Controllers
{
    public class AddPhotoController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            ViewBag.categories = db.Categories.ToList();
            return View();
        }

        [HttpPost]
        public ActionResult Upload(Photo model, HttpPostedFileBase uploadImage)
        {
            var userName = User.Identity.Name;
            byte[] img = null;
            if (uploadImage != null)
            {
                using (var binaryReader = new BinaryReader(uploadImage.InputStream))
                {
                    img = binaryReader.ReadBytes(uploadImage.ContentLength);
                    model.Image = img;
                }

                model.OwnerName = userName;
                if (Request.Form["category"] != "none")
                {
                    var category_name = Request.Form["category"];
                    model.Category = db.Categories.Where(c => c.Name == category_name).FirstOrDefault();
                }
                else if (Request.Form["new_category"] != "")
                {
                    var category = new Category { Name = Request.Form["new_category"] };
                    model.Category = category;
                    db.Categories.Add(category);
                }
                else
                    model.Category = db.Categories.Where(c => c.Name == "None").FirstOrDefault();

                db.Photos.Add(model);
                db.SaveChanges();
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

PhotoGallery/Controllers/HomeController.cs
using PhotoGallery.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace PhotoGallery.Controllers
{
    public class HomeController : Controller
    {
        private static ApplicationDbContext db = new ApplicationDbContext();
        private static string category = "All";

        public ActionResult Index()
        {
            var categories = db.Categories.ToList();
            ViewBag.photos = db.Photos.ToList(); ;
            return View(categories);
        }

        [HttpGet]
        public ActionResult Filter(string categoryName)
        {
            var owner = User.Identity.Name;

            if (categoryName == "All")
            {
                ViewBag.photos = db.Photos.ToList(); 
                category = categoryName;
            }
            else if (categoryName == "Rate")
            {
                if (category == "All")
                    ViewBag.photos = Rate(db.Photos.ToList());
                else if (category == "My")
                    ViewBag.photos = Rate(db.Photos.Where(p => p.OwnerName == owner).ToList());
                else
                    ViewBag.photos = Rate(db.Photos.Where(p => p.Category.Name == category).ToList());
            }
            else if (categoryName == "My")
            {
                ViewBag.photos = db.Photos.Where(p => p.OwnerName == owner).ToList();
                category = categoryName;
            }
            else
            {
                ViewBag.photos = db.Photos.Where(p => p.Category.Name == categoryName).ToList();
                category = categoryName;
            }

            var categories = db.Categories.ToList();

            return View("Index", categories);
        }

        public ActionResult About()
        {
            ViewBag.Message = "This website allows you to publish images and estimate other people publications.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "You can share ideas and suggestions for improving the site here:";

            return View();
        }

        private List<Photo> Rate(List<Photo> photos)
        {
            photos.Sort(new PhotosComperer());

            return photos;
        }

        public ActionResult Admin()
        {
            var photos = db.Photos.ToList();
            return View(photos);
        }

        public JsonResult Delete(int id)
        {
            var bd = new ApplicationDbContext();
            var photo = bd.Photos.Where(p => p.Id == id).FirstOrDefault();
            bd.Photos.Remove(photo);
            bd.SaveChanges();
             
            return Json(true, JsonRequestBehavior.AllowGet);
        }
    }
}

PhotoGallery/Controllers/ViewPhotoController.cs
using PhotoGallery.Models;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;

namespace PhotoGallery.Controllers
{
    public class ViewPhotoController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index(int photoId)
        {
            var photo = db.Photos.Where(p => p.Id == photoId).FirstOrDefault();
            return View(photo);
        }

        [Authorize]
        [HttpPost]
        public JsonResult Like(int id)
        {
            var userName = User.Identity.Name;
            var user = db.Users.Where(u => u.Email == userName).FirstOrDefault();
            var photo = db.Photos.Where(p => p.Id == id).FirstOrDefault();
            var userId = user.Id;

            using (SqlConnection connection = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))
            {
                connection.Open();
                if (photo.IsLiked(userName))
                {
                    SqlCommand command = new SqlCommand($"DELETE FROM ApplicationUserPhotoes WHERE ApplicationUser_Id = '{userId}' AND Photo_Id = '{id}'", connection);
                    command.ExecuteNonQuery();
                }
                else
                {
                    db.Photos.Where(p => p.Id == id).FirstOrDefault().Likes.Add(user);
                    db.SaveChanges();
                }

            }

            return Json(true, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(int photoId)
        {
            var photo = db.Photos.Where(p => p.Id == photoId).FirstOrDefault();
            db.Photos.Remove(photo);
            db.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
    }
}

PhotoGallery/Views/Home/About.cshtml
<h1>Hi!</h1>
<h2>@ViewBag.Message</h2>
<h3>You can post photos, pictures or even digital arts.</h3>
<h3>Good luck!</h3>

PhotoGallery/Views/Home/Admin.cshtml
@using PhotoGallery.Models;
@{
    ViewBag.Title = "Admin Page";
}
@model List<Photo>

<table class="table table-dark table-striped">
    <thead>
        <tr>
            <th>Image</th>
            <th>Description</th>
            <th>Category</th>
            <th>Owner</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var photo in Model)
         { 
            <tr id="@photo.Id">
                <td>@Html.Raw("<img style=\"width: 30px; height: 30px; \" src=\"data:image/jpeg;base64," + Convert.ToBase64String(photo.Image) + "\" />")</td>
                <td>@photo.Description</td>
                <td>@photo.Category.Name</td>
                <td>@photo.OwnerName</td>
                <td><a href="" style="color: white; text-decoration: none" onclick="Delete(@photo.Id)">Delete</a></td>
            </tr>
         }
    </tbody>
</table>

<script type="text/javascript">
    function Delete(id) {
        $.ajax({
            url: "@Url.Action("Delete", "Home")",
            type: "POST",
            data: {
                'id': id
            },
            dataType: 'json',
            success: function () {
                $('#' + id).remove();
                location.reload();
            }
        });
    }
</script>

PhotoGallery/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h1>@ViewBag.Title.</h1>
<h2>@ViewBag.Message</h2>
<h3><a href="">yaroslav.haidai@nure.ua</a></h3>

PhotoGallery/Views/Home/Index.cshtml
@using PhotoGallery.Models;
@{
    ViewBag.Title = "Home Page";
}
@model List<Category>


<div class="row">
    <div class="col-md-3">
        <div class="card">
            <div class="card-header">
                Categories
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    @Html.ActionLink("All", "Filter", "Home", routeValues: new { categoryName = "All" }, htmlAttributes: null)
                </li>
                @foreach (var category in Model)
                {
                    <li class="list-group-item">
                        @Html.ActionLink(category.Name, "Filter", "Home", routeValues: new { categoryName = category.Name }, htmlAttributes: null)
                    </li>
                }

                @Html.ActionLink("Rate", "Filter", "Home", routeValues: new { categoryName = "Rate" }, htmlAttributes: new { @class = "btn btn-block btn-dark btn-sm m-1" })
                @if (Request.IsAuthenticated)
                {
                    @Html.ActionLink("Add Photo", "Index", "AddPhoto", routeValues: null, htmlAttributes: new { @class = "btn btn-block btn-dark btn-sm m-1" })
                    @Html.ActionLink("My Photos", "Filter", "Home", routeValues: new { categoryName = "My" }, htmlAttributes: new { @class = "btn btn-block btn-dark btn-sm m-1" })
                }
            </ul>
        </div>
    </div>
    <div class="col-md-9">
        <div class="row">
            @foreach (var photo in ViewBag.photos)
            {
                <div class="col-md-4">
                    <div class="card my-2">
                        @Html.Raw("<img class=\"image-thumbnail\" src=\"data:image/jpeg;base64,"
                + Convert.ToBase64String(photo.Image) + "\" />")
                        <div class="card-body">
                            <small>Category: @photo.Category.Name</small>
                        </div>
                        @Html.ActionLink("View", "Index", "ViewPhoto", routeValues: new { photoId = photo.Id }, htmlAttributes: new { @class = "btn btn-outline-dark btn-sm m-1" })
                        @if (photo.IsLiked(User.Identity.Name))
                        {
                            <button type="submit" id="like-@photo.Id" onclick="like(@photo.Id)" class="btn btn-block btn-dark btn-sm m-1">Disike @photo.LikesCount()</button>
                        }
                        else
                        {
                            <button type="submit" id="like-@photo.Id" onclick="like(@photo.Id)" class="btn btn-outline-dark btn-sm m-1">Like @photo.LikesCount()</button>
                        }
                    </div>
                </div>
            }
            @if (((List<Photo>)ViewBag.photos).Count() == 0)
            {
                <h3>No photos</h3>
            }
        </div>
    </div>
</div>

<script type="text/javascript">
    function like(id) {
        var like = document.getElementById('like-'+id);
        var likesCount = parseInt(like.innerText.match(/\d+/));
       
        $.ajax({
            url: "@Url.Action("Like", "ViewPhoto")",
            type: "POST",
            data: {
                'id': id
            },
            dataType: 'json',
            success: function () {
                if (like.innerText.startsWith("Like")) {
                    likesCount += 1;
                    like.innerText = "Dislike " + likesCount;
                    like.className = 'btn btn-block btn-dark btn-sm m-1';
                }
                else {
                    likesCount -= 1;
                    like.innerText = "Like " + likesCount;
                    like.className = 'btn btn-outline-dark btn-sm m-1';
                }
            }
        });
    }
</script>